<?php

use Illuminate\Database\Seeder;
use App\TimeZoneModel;
class TimeZoneSeeder extends Seeder
{
    
    public function run()
    {
      DB::table('time_zone')->truncate();
    	$time_zone = [
            ['name'=> 'Alpha Time Zone', 'offset' => 'UTC +1'],
            ['name'=> 'Australian Central Daylight Time', 'offset' => 'UTC +10:30'],
            ['name'=> 'Australian Central Standard Time', 'offset' => 'UTC +9:30'],
            ['name'=> 'Acre Time', 'offset' => 'UTC -5'],     
            ['name'=> 'Australian Central Time', 'offset' => 'UTC +9:30 / +10:30'],
            ['name'=> 'Australian Central Western Standard Time', 'offset' => 'UTC +8:45'],
            ['name'=> 'Arabia Daylight Time', 'offset' => 'UTC +4'],
            ['name'=> 'Atlantic Daylight Time', 'offset' => 'UTC -3'],
            ['name'=> 'Australian Eastern Daylight Time', 'offset' => 'UTC +11'],   
            ['name'=> 'Australian Eastern Standard Time', 'offset' => 'UTC +10'],
            ['name'=> 'Australian Eastern Time', 'offset' => 'UTC +10:00 / +11:00'],
            ['name'=> 'Afghanistan Time', 'offset' => 'UTC +4:30'],
            ['name'=> 'Alaska Daylight Time', 'offset' => 'UTC -8'],
            ['name'=> 'Alaska Standard Time', 'offset' => 'UTC -9'],
            ['name'=> 'Alma-Ata Time', 'offset' => 'UTC +6'],
            ['name'=> 'Amazon Summer Time', 'offset' => 'UTC -3'],
            ['name'=> 'Armenia Summer Time', 'offset' => 'UTC +5'],
            ['name'=> 'Amazon Time', 'offset' => 'UTC -4'],
            ['name'=> 'Armenia Time', 'offset' => 'UTC +4'],
            ['name'=> 'Anadyr Summer Time', 'offset' => 'UTC +12'],
            ['name'=> 'Anadyr Time', 'offset' => 'UTC +12'],
            ['name'=> 'Aqtobe Time', 'offset' => 'UTC +5'],
            ['name'=> 'Argentina Time', 'offset' => 'UTC -3'],
            ['name'=> 'Arabia Standard Time', 'offset' => 'UTC +3'],
            ['name'=> 'Atlantic Standard Time', 'offset' => 'UTC -4'],
            ['name'=> 'Atlantic Time', 'offset' => 'UTC -4:00 / -3:00'],
            ['name'=> 'Australian Western Daylight Time', 'offset' => 'UTC +9'],
            ['name'=> 'Australian Western Standard Time', 'offset' => 'UTC +8'],
            ['name'=> 'Azores Summer Time', 'offset' => 'UTC +0'],
            ['name'=> 'Azores Time', 'offset' => 'UTC -1'],
            ['name'=> 'Azerbaijan Summer Time', 'offset' => 'UTC +5'],
            ['name'=> 'Azerbaijan Time', 'offset' => 'UTC +4'],
            ['name'=> 'Anywhere on Earth', 'offset' => 'UTC -12'],

            ['name'=> 'Bravo Time Zone', 'offset' => 'UTC +2'],
            ['name'=> 'Brunei Darussalam Time', 'offset' => 'UTC +8'],
            ['name'=> 'Bolivia Time', 'offset' => 'UTC -4'],
            ['name'=> 'Brasília Summer Time', 'offset' => 'UTC -2'],
            ['name'=> 'Brasília Time', 'offset' => 'UTC -3'],
            ['name'=> 'Bangladesh Standard Time', 'offset' => 'UTC +6'],
            ['name'=> 'Bougainville Standard Time', 'offset' => 'UTC +11'],
            ['name'=> 'British Summer Time', 'offset' => 'UTC +1'],
            ['name'=> 'Bhutan Time', 'offset' => 'UTC +6'],

            ['name'=> 'Charlie Time Zone', 'offset' => 'UTC +3'],
            ['name'=> 'Casey Time', 'offset' => 'UTC +8'],
            ['name'=> 'Central Africa Time', 'offset' => 'UTC +2'],
            ['name'=> 'Cocos Islands Time', 'offset' => 'UTC +6:30'],
            ['name'=> 'Central Daylight Time', 'offset' => 'UTC -5'],
            ['name'=> 'Cuba Daylight Time', 'offset' => 'UTC -4'],
            ['name'=> 'Central European Summer Time', 'offset' => 'UTC +2'],
            ['name'=> 'Central European Time', 'offset' => 'UTC +1'],
            ['name'=> 'Chatham Island Daylight Time', 'offset' => 'UTC +13:45'],
            ['name'=> 'Chatham Island Standard Time', 'offset' => 'UTC +12:45'],
            ['name'=> 'Choibalsan Summer Time', 'offset' => 'UTC +9'],
            ['name'=> 'Choibalsan Time', 'offset' => 'UTC +8'],
            ['name'=> 'Chuuk Time', 'offset' => 'UTC +10'],
            ['name'=> 'Cayman Islands Daylight Saving Time', 'offset' => 'UTC -4'],
            ['name'=> 'Cayman Islands Standard Time', 'offset' => 'UTC -5'],
            ['name'=> 'Cook Island Time', 'offset' => 'UTC -10'],
            ['name'=> 'Chile Summer Time', 'offset' => 'UTC -3'],
            ['name'=> 'Chile Standard Time', 'offset' => 'UTC -4'],
            ['name'=> 'Colombia Time', 'offset' => 'UTC -5'],
            ['name'=> 'Central Standard Time', 'offset' => 'UTC -6'],
            ['name'=> 'China Standard Time', 'offset' => 'UTC +8'],
            ['name'=> 'Cuba Standard Time', 'offset' => 'UTC -5'],
            ['name'=> 'Central Time', 'offset' => 'UTC -6:00 / -5:00'],
            ['name'=> 'Cape Verde Time', 'offset' => 'UTC -1'],
            ['name'=> 'Christmas Island Time', 'offset' => 'UTC +7'],
            ['name'=> 'Chamorro Standard Time', 'offset' => 'UTC +10'],

            ['name'=> 'Delta Time Zone', 'offset' => 'UTC +4'],
            ['name'=> 'Davis Time', 'offset' => 'UTC +7'],
            ['name'=> "Dumont-d'Urville Time", 'offset' => 'UTC +10'],

            ['name'=> 'Echo Time Zone', 'offset' => 'UTC +5'],
            ['name'=> 'Easter Island Summer Time', 'offset' => 'UTC -5'],
            ['name'=> 'Easter Island Standard Time', 'offset' => 'UTC -6'],
            ['name'=> 'Eastern Africa Time', 'offset' => 'UTC +3'],
            ['name'=> 'Ecuador Time', 'offset' => 'UTC -5'],
            ['name'=> 'Eastern Daylight Time', 'offset' => 'UTC -4'],
            ['name'=> 'Eastern European Summer Time', 'offset' => 'UTC +3'],
            ['name'=> 'Eastern European Time', 'offset' => 'UTC +2'],
            ['name'=> 'Eastern Greenland Summer Time', 'offset' => 'UTC +0'],
            ['name'=> 'East Greenland Time', 'offset' => 'UTC -1'],
            ['name'=> 'Eastern Standard Time', 'offset' => 'UTC -5'],
            ['name'=> 'Eastern Time', 'offset' => 'UTC -5:00 / -4:00'],

            ['name'=> 'Foxtrot Time Zone ', 'offset' => 'UTC +6'],
            ['name'=> 'Further-Eastern European Time', 'offset' => 'UTC +3'],
            ['name'=> 'Fiji Summer Time', 'offset' => 'UTC +13'],
            ['name'=> 'Falkland Islands Summer Time', 'offset' => 'UTC -3'],
            ['name'=> 'Falkland Island Time', 'offset' => 'UTC -4'],
            ['name'=> 'Fernando de Noronha Time', 'offset' => 'UTC -2'],

            ['name'=> 'Golf Time Zone', 'offset' => 'UTC +7'],
            ['name'=> 'Galapagos Time', 'offset' => 'UTC -6'],
            ['name'=> 'Gambier Time', 'offset' => 'UTC -9'],
            ['name'=> 'Georgia Standard Time', 'offset' => 'UTC +4'],
            ['name'=> 'French Guiana Time', 'offset' => 'UTC -3'],
            ['name'=> 'Gilbert Island Time', 'offset' => 'UTC +12'],
            ['name'=> 'Greenwich Mean Time', 'offset' => 'UTC +0'],
            ['name'=> 'Gulf Standard Time', 'offset' => 'UTC +4'],
            ['name'=> 'South Georgia Time', 'offset' => 'UTC -2'],
            ['name'=> 'Guyana Time', 'offset' => 'UTC -4'],

            ['name'=> 'Hotel Time Zone', 'offset' => 'UTC +8'],
            ['name'=> 'Hawaii-Aleutian Daylight Time', 'offset' => 'UTC -9'],
            ['name'=> 'Hong Kong Time', 'offset' => 'UTC +8'],
            ['name'=> 'Hovd Time', 'offset' => 'UTC +7'],
            ['name'=> 'Hawaii Standard Time', 'offset' => 'UTC -10'],

            ['name'=> 'India Time Zone', 'offset' => 'UTC +9'],
            ['name'=> 'Indochina Time', 'offset' => 'UTC +7'],
            ['name'=> 'Israel Daylight Time', 'offset' => 'UTC +3'],
            ['name'=> 'Indian Chagos Time', 'offset' => 'UTC +6'],
            ['name'=> 'Iran Daylight Time', 'offset' => 'UTC +4:30'],
            ['name'=> 'Irkutsk Summer Time', 'offset' => 'UTC +9'],
            ['name'=> 'Irkutsk Time', 'offset' => 'UTC +8'],
            ['name'=> 'Iran Standard Time', 'offset' => 'UTC +3:30'],
            ['name'=> 'India Standard Time', 'offset' => 'UTC +5:30'],
            ['name'=> '	Irish Standard Time', 'offset' => 'UTC +1'],
            ['name'=> 'Israel Standard Time', 'offset' => 'UTC +2'],

            ['name'=> 'Japan Standard Time', 'offset' => 'UTC +9'],

            ['name'=> 'Kilo Time Zone', 'offset' => 'UTC +10'],
            ['name'=> 'Kyrgyzstan Time', 'offset' => 'UTC +6'],
            ['name'=> 'Kosrae Time', 'offset' => 'UTC +11'],
            ['name'=> 'Krasnoyarsk Summer Time', 'offset' => 'UTC +8'],
            ['name'=> 'Krasnoyarsk Time', 'offset' => 'UTC +7'],
            ['name'=> 'Korea Standard Time', 'offset' => 'UTC +9'],
            ['name'=> 'Kuybyshev Time', 'offset' => 'UTC +4'],

            ['name'=> 'Lima Time Zone', 'offset' => 'UTC +11'],
            ['name'=> 'Lord Howe Daylight Time', 'offset' => 'UTC +11'],
            ['name'=> 'Lord Howe Standard Time', 'offset' => 'UTC +10:30'],
            ['name'=> 'Line Islands Time', 'offset' => 'UTC +14'],

            ['name'=> 'Mike Time Zone', 'offset' => 'UTC +12'],
            ['name'=> 'Magadan Summer Time', 'offset' => 'UTC +12'],
            ['name'=> 'Magadan Time', 'offset' => 'UTC +11'],
            ['name'=> 'Marquesas Time', 'offset' => 'UTC -9:30'],
            ['name'=> 'Mawson Time', 'offset' => 'UTC +5'],
            ['name'=> 'Mountain Daylight Time', 'offset' => 'UTC -6'],
            ['name'=> 'Marshall Islands Time', 'offset' => 'UTC +12'],
            ['name'=> 'Myanmar Time', 'offset' => 'UTC +6:30'],
            ['name'=> 'Moscow Daylight Time', 'offset' => 'UTC +4'],
            ['name'=> 'Moscow Standard Time', 'offset' => 'UTC +3'],
            ['name'=> 'Mountain Standard Time', 'offset' => 'UTC -7'],
            ['name'=> 'Mountain Time', 'offset' => 'UTC -7:00 / -6:00'],
            ['name'=> 'Mauritius Time', 'offset' => 'UTC +4'],
            ['name'=> 'Maldives Time', 'offset' => 'UTC +5'],
            ['name'=> 'Malaysia Time', 'offset' => 'UTC +8'],

            ['name'=> 'November Time Zone', 'offset' => 'UTC -1'],
            ['name'=> 'New Caledonia Time', 'offset' => 'UTC +11'],
            ['name'=> 'Newfoundland Daylight Time', 'offset' => 'UTC -2:30'],
            ['name'=> 'Norfolk Daylight Time', 'offset' => 'UTC +12'],
            ['name'=> 'Norfolk Time', 'offset' => 'UTC +11'],
            ['name'=> 'Novosibirsk Summer Time', 'offset' => 'UTC +7'],
            ['name'=> 'Novosibirsk Time', 'offset' => 'UTC +7'],
            ['name'=> 'Nepal Time', 'offset' => 'UTC +5:45'],
            ['name'=> 'Newfoundland Standard Time', 'offset' => 'UTC -3:30'],
            ['name'=> 'Niue Time', 'offset' => 'UTC -11'],
            ['name'=> 'New Zealand Daylight Time', 'offset' => 'UTC +13'],
            ['name'=> 'New Zealand Standard Time', 'offset' => 'UTC +12'],

            ['name'=> 'Oscar Time Zone', 'offset' => 'UTC -2'],
            ['name'=> 'Omsk Summer Time', 'offset' => 'UTC +7'],
            ['name'=> 'Omsk Standard Time', 'offset' => 'UTC +6'],
            ['name'=> 'Oral Time', 'offset' => 'UTC +5'],

            ['name'=> 'Papa Time Zone', 'offset' => 'UTC -3'],
            ['name'=> 'Pacific Daylight Time', 'offset' => 'UTC -7'],
            ['name'=> 'Peru Time', 'offset' => 'UTC -5'],
            ['name'=> 'Kamchatka Summer Time ', 'offset' => 'UTC +12'],
            ['name'=> 'Kamchatka Time', 'offset' => 'UTC +12'],
            ['name'=> 'Papua New Guinea Time', 'offset' => 'UTC +10'],
            ['name'=> 'Phoenix Island Time', 'offset' => 'UTC +13'],
            ['name'=> 'Philippine Time', 'offset' => 'UTC +8'],
            ['name'=> 'Pakistan Standard Time', 'offset' => 'UTC +5'],
            ['name'=> 'Pierre & Miquelon Daylight Time', 'offset' => 'UTC -2'],
            ['name'=> 'Pierre & Miquelon Standard Time', 'offset' => 'UTC -3'],
            ['name'=> 'Pohnpei Standard Time ', 'offset' => 'UTC +11'],
            ['name'=> 'Pacific Standard Time', 'offset' => 'UTC -8'],
            ['name'=> 'Pitcairn Standard Time', 'offset' => 'UTC -8'],
            ['name'=> 'Pacific Time', 'offset' => 'UTC -8:00 / -7:00'],
            ['name'=> 'Palau Time', 'offset' => 'UTC +9'],
            ['name'=> 'Paraguay Summer Time', 'offset' => 'UTC -3'],
            ['name'=> 'Paraguay Time', 'offset' => 'UTC -4'],
            ['name'=> 'Pyongyang Time', 'offset' => 'UTC +8:30'],

            ['name'=> 'Quebec Time Zone ', 'offset' => 'UTC -4'],
            ['name'=> 'Qyzylorda Time ', 'offset' => 'UTC +6'],

            ['name'=> 'Romeo Time Zone', 'offset' => 'UTC -5'],
            ['name'=> 'Reunion Time', 'offset' => 'UTC +4'],
            ['name'=> 'Rothera Time', 'offset' => 'UTC -3'],

            ['name'=> 'Sierra Time Zone', 'offset' => 'UTC -6'],
            ['name'=> 'Sakhalin Time', 'offset' => 'UTC +11'],
            ['name'=> 'Samara Time', 'offset' => 'UTC +4'],
            ['name'=> 'South Africa Standard Time', 'offset' => 'UTC +2'],
            ['name'=> 'Solomon Islands Time', 'offset' => 'UTC +11'],
            ['name'=> 'Seychelles Time', 'offset' => 'UTC +4'],
            ['name'=> 'Singapore Time', 'offset' => 'UTC +8'],
            ['name'=> 'Srednekolymsk Time', 'offset' => 'UTC +11'],
            ['name'=> 'Suriname Time', 'offset' => 'UTC -3'],
            ['name'=> 'Samoa Standard Time', 'offset' => 'UTC -11'],
            ['name'=> 'Syowa Time', 'offset' => 'UTC +3'],

            ['name'=> 'Tango Time Zone', 'offset' => 'UTC -7'],
            ['name'=> 'Tahiti Time', 'offset' => 'UTC -10'],
            ['name'=> 'Tajikistan Time', 'offset' => 'UTC +5'],
            ['name'=> 'Tokelau Time', 'offset' => 'UTC +13'],
            ['name'=> 'East Timor Time', 'offset' => 'UTC +9'],
            ['name'=> 'Turkmenistan Time', 'offset' => 'UTC +5'],
            ['name'=> 'Tonga Summer Time', 'offset' => 'UTC +14'],
            ['name'=> 'Tonga Time', 'offset' => 'UTC +13'],
            ['name'=> 'Turkey Time', 'offset' => 'UTC +3'],
            ['name'=> 'Tuvalu Time', 'offset' => 'UTC +12'],

            ['name'=> 'Uniform Time Zone', 'offset' => 'UTC -8'],
            ['name'=> 'Ulaanbaatar Summer Time', 'offset' => 'UTC +9'],
            ['name'=> 'Ulaanbaatar Time', 'offset' => 'UTC +8'],
            ['name'=> 'Coordinated Universal Time', 'offset' => 'UTC'],
            ['name'=> 'Uruguay Summer Time', 'offset' => 'UTC -2'],
            ['name'=> 'Uruguay Time', 'offset' => 'UTC -3'],
            ['name'=> 'Uzbekistan Time', 'offset' => 'UTC +5'],

            ['name'=> 'Victor Time Zone', 'offset' => 'UTC -9'],
            ['name'=> 'Venezuelan Standard Time', 'offset' => 'UTC -4'],
            ['name'=> 'Vladivostok Summer Time', 'offset' => 'UTC +11'],
            ['name'=> 'Vladivostok Time', 'offset' => 'UTC +10'],
            ['name'=> 'Vostok Time', 'offset' => 'UTC +6'],
            ['name'=> 'Vanuatu Time', 'offset' => 'UTC +11'],

            ['name'=> 'Whiskey Time Zone', 'offset' => 'UTC -10'],
            ['name'=> 'Wake Time', 'offset' => 'UTC +12'],
            ['name'=> 'Western Argentine Summer Time', 'offset' => 'UTC -3'],
            ['name'=> 'West Africa Summer Time', 'offset' => 'UTC +2'],
            ['name'=> 'West Africa Time', 'offset' => 'UTC +1'],
            ['name'=> 'Western European Summer Time', 'offset' => 'UTC +1'],
            ['name'=> 'Western European Time', 'offset' => 'UTC +0'],
            ['name'=> 'Wallis and Futuna Time', 'offset' => 'UTC +12'],
            ['name'=> 'Western Greenland Summer Time', 'offset' => 'UTC -2'],
            ['name'=> 'West Greenland Time', 'offset' => 'UTC -3'],
            ['name'=> 'Western Indonesian Time', 'offset' => 'UTC +7'],
            ['name'=> 'Eastern Indonesian Time', 'offset' => 'UTC +9'],
            ['name'=> 'Central Indonesian Time', 'offset' => 'UTC +8'],
            ['name'=> 'West Samoa Time', 'offset' => 'UTC +14'],
            ['name'=> 'Western Sahara Summer Time', 'offset' => 'UTC +1'],
            ['name'=> 'Western Sahara Standard Time', 'offset' => 'UTC +0'],

            ['name'=> 'X-ray Time Zone', 'offset' => 'UTC -11'],

            ['name'=> 'Yankee Time Zone', 'offset' => 'UTC -12'],
            ['name'=> 'Yakutsk Summer Time', 'offset' => 'UTC +10'],
            ['name'=> 'Yakutsk Time ', 'offset' => 'UTC +9'],
            ['name'=> 'Yap Time', 'offset' => 'UTC +10'],
            ['name'=> 'Yekaterinburg Summer Time', 'offset' => 'UTC +6'],
            ['name'=> 'Yekaterinburg Time', 'offset' => 'UTC +5'],
            
            ['name'=> 'Zulu Time Zone', 'offset' => 'UTC +0'],
           
          ];

      foreach($time_zone as $tz)
      {
        DB::table('time_zone')->insert($tz);
        
      }

    }
}
